/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sneha
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class add_rotine extends javax.swing.JFrame {

    /**
     * Creates new form add_rotine
     */
    public static String sid,fid,year;
    public add_rotine() {
        initComponents();
        dbcon obj = new dbcon();
        Connection con=obj.connection();
        String str ="select * from unims.course z join subjects b on z.courseid=b.courseid ";
        String s ="SELECT * FROM unims.course;";
        try{
            Statement  stm = con.createStatement();
           ResultSet rs = stm.executeQuery(s);
           while(rs.next())
           {
               
               cnm.addItem(rs.getString(1));
           }
        }
        catch(Exception e)
        {
            
        }
    }
    public static int p;
    public static int d;
     public add_rotine(String  sid,String fid,int p,int d) {
        initComponents();
        dbcon obj = new dbcon();
        Connection con=obj.connection();
        this.sid=sid;
        this.fid=fid;
        this.p=p;
        this.d=d;
        String str ="select * from unims.course z join subjects b on z.courseid=b.courseid ";
        String s ="SELECT * FROM unims.course;";
        try{
            Statement  stm = con.createStatement();
           ResultSet rs = stm.executeQuery(s);
           while(rs.next())
           {
               
               cnm.addItem(rs.getString(1));
           }
        }
        catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cnm = new javax.swing.JComboBox<>();
        ye = new javax.swing.JComboBox<>();
        section = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("course");

        jLabel2.setText("year");

        jLabel3.setText("sec");

        cnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnmActionPerformed(evt);
            }
        });

        ye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yeActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cnm, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ye, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton1)))
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnmActionPerformed
        // TODO add your handling code here:
        ye.removeAllItems();
        String st="select * from unims.section group by(yer) having cid='"+String.valueOf(cnm.getSelectedItem())+"'";
        System.out.println(st);
         dbcon obj = new dbcon();
        Connection con=obj.connection();
        try{
            Statement  stm = con.createStatement();
           ResultSet rs = stm.executeQuery(st);
           while(rs.next())
           {
               
               ye.addItem(rs.getString(2));
           }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_cnmActionPerformed

    private void yeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yeActionPerformed
        // TODO add your handling code here:
        section.removeAllItems();
        String st ="select sec from unims.section where cid='"+String.valueOf(cnm.getSelectedItem())+"' and yer="+String.valueOf(ye.getSelectedItem())+";";
        dbcon obj = new dbcon();
        Connection con=obj.connection();
        try{
            Statement  stm = con.createStatement();
           ResultSet rs = stm.executeQuery(st);
           while(rs.next())
           {
               
               section.addItem(rs.getString(1));
           }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_yeActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String str = "insert into unims.rotuin values ('"+String.valueOf(section.getSelectedItem())+"','"+String.valueOf(cnm.getSelectedItem())+"','"+fid+"','"+sid+"',"+d+","+p+",'"+String.valueOf(ye.getSelectedItem())+"');";
        dbcon obj = new dbcon();
        Connection con=obj.connection();
        try{
            Statement  stm = con.createStatement();
           stm.execute(str);
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Facuilty is busy");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_rotine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_rotine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_rotine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_rotine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_rotine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cnm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> section;
    private javax.swing.JComboBox<String> ye;
    // End of variables declaration//GEN-END:variables
}
